<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\tModLoader.targets" />

    <PropertyGroup>
        <AssemblyName>PointShop</AssemblyName>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="SilkyUIFramework">
            <HintPath>libs\SilkyUIFramework.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Solaestas.tModLoader.ModBuilder" Version="1.6.1" />
        <PackageReference Include="YamlDotNet" Version="16.3.0" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="**/*.yaml;**/*.yml" Exclude="bin/**/*;obj/**/*" Pack="true" ModPath="%(Identity)" />
    </ItemGroup>

</Project>